# docker/docker-compose.yml
version: '3'

services:
  node:
    image: "node:13"
    # restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "npm run watch-be"
    ports:
     - "6060:6060"
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASS
    ports:
     - "6379:6379"