# docker/docker-compose.yml
version: '3'

services:
  node:
    image: "node:13"
    # restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "npm run watch-be"
    ports:
     - "6060:6060"
    env_file:
      - .env
    depends_on:
     - mongo
     - redis
  frontend:
    image: "node:13"
    # restart: always
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "npm run start"
    ports:
     - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    depends_on:
     - mongo
     - redis
     - node
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass $REDIS_PASS
    ports:
     - "6379:6379"
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
     - "27117:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: texel